

[functions.check-email-config]
verify_jwt = true

[functions.resend-invitation]
verify_jwt = true

[functions.send-invite-email]
verify_jwt = true

[functions.send-email-sendgrid]
verify_jwt = true

